# Generated by Django 4.2.2 on 2023-06-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college_details',
            options={'verbose_name_plural': 'College_Details'},
        ),
    ]
