# Generated by Django 4.2.2 on 2023-06-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_college_details_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='co_import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('co_number', models.CharField(max_length=100)),
                ('course_outcome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'co_import',
            },
        ),
    ]
