# Generated by Django 4.2.2 on 2023-06-13 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_pso_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='unit_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('unit_one', models.IntegerField()),
                ('unit_two', models.IntegerField()),
                ('unit_three', models.IntegerField()),
                ('unit_four', models.IntegerField()),
                ('unit_five', models.IntegerField()),
                ('co_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_co', to='settings.co_import')),
            ],
            options={
                'verbose_name_plural': 'unit_datails',
            },
        ),
        migrations.CreateModel(
            name='assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('course_outcome', models.CharField(max_length=100)),
                ('assessment_tools', models.CharField(max_length=100)),
                ('assessment_weightages', models.CharField(max_length=100)),
                ('co_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_name', to='settings.co_import')),
            ],
            options={
                'verbose_name_plural': 'assessment',
            },
        ),
    ]
