# Generated by Django 4.1.6 on 2023-07-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_unit_details_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='target_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('target_value', models.IntegerField()),
                ('grade_target_value', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'target_value',
            },
        ),
    ]
