# Generated by Django 4.1.6 on 2023-07-13 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_target_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('po_details', models.CharField(max_length=50)),
                ('pso_details', models.CharField(max_length=50)),
                ('co_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attainment_name', to='settings.co_import')),
            ],
            options={
                'verbose_name_plural': 'Attainment',
            },
        ),
    ]
