# Generated by Django 4.1.6 on 2023-07-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_attainment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attainment',
            name='po_details',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='attainment',
            name='pso_details',
            field=models.JSONField(),
        ),
    ]
