# Generated by Django 4.1.6 on 2023-07-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_attainment_po_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target_value',
            name='target_mark',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
