# Generated by Django 4.1.6 on 2023-07-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_target_value_target_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target_value',
            name='target_mark',
            field=models.CharField(max_length=50),
        ),
    ]
