# Generated by Django 4.2.2 on 2023-06-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'course',
            },
        ),
    ]
