# Generated by Django 4.2.2 on 2023-06-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='course_name',
            new_name='course_datils',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
    ]
