# Generated by Django 4.2.2 on 2023-06-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_rename_course_name_subject_course_datils_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='course_datils',
            new_name='course_details',
        ),
    ]
