# Generated by Django 4.2.2 on 2023-06-15 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_rename_course_datils_subject_course_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('register_number', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('course_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_course', to='academic.course')),
            ],
            options={
                'verbose_name_plural': 'student',
            },
        ),
    ]
