# Generated by Django 4.1.6 on 2023-06-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_question_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_pattern',
            name='unit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
