# Generated by Django 4.1.6 on 2023-06-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_question_pattern_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
