# Generated by Django 4.2.2 on 2023-06-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_remove_course_academic_year_student_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_pattern',
            name='marks_allotted',
            field=models.IntegerField(),
        ),
    ]
