# Generated by Django 4.2.2 on 2023-06-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=1, max_length=100, verbose_name='role'),
            preserve_default=False,
        ),
    ]
